name: Deployment - Reusable Workflow
on:
  workflow_call:
jobs:
    reuse-deploy:
      environment:
        name: development
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      outputs:
        APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}


      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.36.1'

        - name: Setup Kubeconfig
          uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}

        - name: Fetch Kubernetes config
          run: |
            kubectl version --client
            echo ------------------------------------------------
            kubectl get nodes

        - name: Save Nginx Ingress Controller IP as an environment variable
          run: |
            echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

        - name: Replace Tokens in Manifest files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '${'
            tokenSuffix: '}'
            files: '["kubernetes/development/*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            K8S_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check Manifest files after token replacement
          run: |
            cat kubernetes/development/*.yaml

        - name: Check Files
          run: |
            ls -al
            ls -al kubernetes/development/*.yaml
            cat kubernetes/development/service.yaml

        - name: Create MongoDB Secret
          run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

        - name: Deploy to Development Environment
          run: |
            kubectl apply -f kubernetes/development/

        - name: Wait for deployment rollout
          run: |
            kubectl -n ${{ vars.NAMESPACE }} rollout status deployment/solar-system --timeout=150s

        - name: Set App Ingress host URL
          id: set-ingress-host-address
          run: |
            echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress solar-system -o jsonpath='{.spec.rules[0].host}')" >> "$GITHUB_OUTPUT"


            